//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantas_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class ficha
    {
        public ficha()
        {
            this.categoria = new HashSet<categoria>();
        }
    
        public int idficha { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string link { get; set; }
        public bool activo { get; set; }
        public string img_url { get; set; }
    
        public virtual ICollection<categoria> categoria { get; set; }
    }
}
